#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  leftIEM,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  rightIEM,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           DriveBL,       tmotorVex393, openLoop)
#pragma config(Motor,  port2,           IntakeL,       tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port3,           LiftBR,        tmotorVex269, openLoop, reversed)
#pragma config(Motor,  port4,           LiftBL,        tmotorVex269, openLoop)
#pragma config(Motor,  port5,           DriveFR,       tmotorVex393HighSpeed, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port6,           DriveFL,       tmotorVex393HighSpeed, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port7,           LiftFL,        tmotorVex269, openLoop)
#pragma config(Motor,  port8,           LiftFR,        tmotorVex269, openLoop)
#pragma config(Motor,  port9,           IntakeR,       tmotorVex269, openLoop)
#pragma config(Motor,  port10,          DriveBR,       tmotorVex393HighSpeed, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*+++++++++++++++++++++++++++++++++++++++++++++| Notes |++++++++++++++++++++++++++++++++++++++++++++++
Move Forward and Display Values - 269 Motors
This program instructs your robot to move forward at half power for 1000 encoder counts. It will
display the encoder values on the VEX LCD. There is a two second pause at the beginning of the program.

Robot Model(s): Modified Squarebot

[I/O Port]          [Name]              [Type]                [Description]
Motor Port 1        rightMotor          393 Motor             Right side motor
Motor Port 10       leftMotor           393 Motor             Left side motor, Reversed
I2C_1               rightIEM            Integrated Encoder    Encoder mounted on rightMotor
I2C_2               leftIEM             Integrated Encoder    Encoted mounted on leftMotor
UART2               -------             VEX LCD               VEX LCD, Optional
----------------------------------------------------------------------------------------------------*/

task main
{
	wait1Msec(2000);

	//Setup the VEX LCD for displaying encoder values
	clearLCDLine(0);
	clearLCDLine(1);
	displayLCDString(0, 0, "R: ");
	displayLCDString(1, 0, "L: ");

	//Clear the encoders associated with the left and right motors
	nMotorEncoder[DriveFR] = 0;
	nMotorEncoder[DriveFL] = 0;

	//While less than 1000 encoder counts of the right motor
	while(nMotorEncoder[DriveFL] < 1000)
	{
		//Display the right and left motor encoder values
		displayLCDNumber(0, 3, nMotorEncoder[DriveFR], 6);
		displayLCDNumber(1, 3, nMotorEncoder[DriveFL], 6);
		//Move forward at half power
		motor[DriveBL] = 63;
		motor[DriveFL]	= 63;
		motor[DriveBR] = 63;
		motor[DriveFR]	= 63;

	}
}
