#pragma config(Sensor, dgtl11, QuadEncoder,         sensorQuadEncoder)
#pragma config(Motor,  port5,           mtr5,          tmotorNormal, openLoop)
#pragma config(Motor,  port6,           mtr6,          tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task EncoderDisplay()
{
	int EncoderTicks = 0;
	while(true)
	{
		EncoderTicks = SensorValue[QuadEncoder];
		displayLCDString(1, 0, "Encoders:        ");
		displayLCDNumber(1, 10, EncoderTicks);
		wait1Msec(100);
	}
}

task main()
{
	bLCDBacklight = true;
	clearLCDLine(0);
	clearLCDLine(1);
	//displayLCDString(1, 0, "Delay: 5 Sec");

	SensorValue[QuadEncoder] = 0;
	wait1Msec(200);
	StartTask(EncoderDisplay);
	while(true)
	{
		displayLCDString(0, 0, "Motors 5+6 Fwd ");
		//displayLCDNumber(1, 12, 127);
		SensorValue[QuadEncoder] = 0;
		motor[mtr5] = 127;
		motor[mtr6] = 127;
		wait1Msec(5000);
		motor[mtr5] = 0;
		motor[mtr6] = 0;
		displayLCDString(0, 0, "Press a Button");
		while (!nLCDButtons);
		wait1Msec(250);
		displayLCDString(0, 0, "Motors 5+6 Bwd ");
		//displayLCDNumber(1, 12, 127);
		SensorValue[QuadEncoder] = 0;
		motor[mtr5] = -127;
		motor[mtr6] = -127;
		wait1Msec(5000);
		motor[mtr5] = 0;
		motor[mtr6] = 0;
		displayLCDString(0, 0, "Press a Button");
		while (!nLCDButtons);
		wait1Msec(250);
	}
}
