#pragma config(UART_Usage, UART2, VEX_2x16_LCD, baudRate1200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    Gyro,           sensorGyro)
#pragma config(Sensor, in2,    LeftLineFollowerPort, sensorLineFollower)
#pragma config(Sensor, in3,    RightLineFollowerPort, sensorLineFollower)
#pragma config(Sensor, in4,    CdS,            sensorReflection)
#pragma config(Sensor, dgtl1,  VariableEncoderPort, sensorQuadEncoder)
#pragma config(Sensor, dgtl10, TinesPort,      sensorDigitalOut)
#pragma config(Sensor, dgtl11, LiftEncoderPort, sensorQuadEncoder)
#pragma config(Sensor, I2C_1,  IMEDriveFR,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  IMEDriveFL,     sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  IMELift,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           DriveBL,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           IntakeL,       tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           LiftBR,        tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           LiftBL,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           DriveFR,       tmotorServoContinuousRotation, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port6,           DriveFL,       tmotorServoContinuousRotation, openLoop, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port7,           LiftFL,        tmotorServoContinuousRotation, openLoop, encoder, encoderPort, I2C_3, 1000)
#pragma config(Motor,  port8,           LiftFR,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           IntakeR,       tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port10,          DriveBR,       tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int StickX;
int StickY;
int StickZ;
int ButtonLiftUp;
int ButtonLiftDown;
int ButtonIntakeIn;
int ButtonIntakeOut;
int MotorFrontLeftDrive;
int MotorFrontRightDrive;
int MotorBackLeftDrive;
int MotorBackRightDrive;
int MotorFrontLeftLift;
int MotorFrontRightLift;
int MotorBackLeftLift;
int MotorBackRightLift;
int MotorIntakeLeft;
int MotorIntakeRight;

task main();
{
	while(true)
	{
		StickX = vexRT[Ch4];
		StickY = vexRT[Ch3];
		StickZ = vexRT[Ch1];
		ButtonLiftUp = vexRT[Btn5U];
		ButtonLiftDown = vexRT[Btn5D];
		ButtonIntakeIn = vexRT[Btn6U];
		ButtonIntakeOut = vexRT[Btn6D];

		MotorFrontLeftDrive = StickY;
		MotorFrontRightDrive = StickY;
		MotorBackLeftDrive = StickY;
		MotorBackRightDrive =  StickY;
		MotorFrontLeftLift = (ButtonLiftUp - ButtonLiftDown) * 127;
		MotorFrontRightLift = (ButtonLiftUp - ButtonLiftDown) * 127;
		MotorBackLeftLift = (ButtonLiftUp - ButtonLiftDown) * 127;
		MotorBackRightLift = (ButtonLiftUp - ButtonLiftDown) * 127;
		MotorIntakeLeft = (ButtonIntakeIn - ButtonIntakeOut) * 127;
		MotorIntakeRight = (ButtonIntakeIn - ButtonIntakeOut) * 127;

		motor[DriveFL] = MotorFrontLeftDrive;
		motor[DriveFR] = MotorFrontRightDrive;
		motor[DriveBL] = MotorBackLeftDrive;
		motor[DriveBR] = MotorBackRightDrive;
		motor[LiftFL] = MotorFrontLeftLift;
		motor[LiftFR] = MotorFrontRightLift;
		motor[LiftBL] = MotorBackLeftLift;
		motor[LiftBR] = MotorBackRightLift;
		motor[IntakeL] = MotorIntakeLeft;
		motor[IntakeR] = MotorIntakeRight;
	}

}
