#pragma config(Sensor, in1,    LIFT_POT,       sensorPotentiometer)
#pragma config(Sensor, in2,    AUTO_POT,       sensorPotentiometer)
#pragma config(Sensor, in3,    GYRO,           sensorGyro)
#pragma config(Sensor, in4,    POW_EX_V,       sensorAnalog)
#pragma config(Sensor, dgtl1,  LEFT_ENC,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RIGHT_ENC,      sensorQuadEncoder)
#pragma config(Motor,  port1,           DRV_F_L,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port2,           DRV_F_R,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port3,           DRV_B_L,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port4,           DRV_B_R,       tmotorVex393HighSpeed, openLoop)
#pragma config(Motor,  port5,           LIFT_L_1,      tmotorVex393, openLoop)
#pragma config(Motor,  port6,           LIFT_L_2,      tmotorVex393, openLoop)
#pragma config(Motor,  port7,           LIFT_R_1,      tmotorVex393, openLoop)
#pragma config(Motor,  port8,           LIFT_R_2,      tmotorVex393, openLoop)
#pragma config(Motor,  port9,           INTAKE_1,      tmotorVex393, openLoop)
#pragma config(Motor,  port10,          INTAKE_2,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//////////////////////
//  Main.c          //
//  Joseph Dykstra  //
//  VRC team 3018   //
//  2013-11-25      //
//  2013-xx-xx      //
//////////////////////

#include "Globals.c"
#include "Initialize.c"
#include "OtherFuncs.c"
#include "Input.c"
#include "Operator.c"
#include "Autos/autoBlueHang.c"
#include "Autos/autoBlueMid.c"
#include "Autos/autoRedHang.c"
#include "Autos/autoRedMid.c"
#include "Autonomous.c"
#include "Output.c"
#ifdef USE_SCREEN
	#include "LCD.c"
#endif

task main()
	{
	initialize();
	while(1)
		{
		input();
		switch (sysCurrentMode)
			{
			case AUTONOMOUS: processAutonomous(); break;
			case OPERATOR:   processOperator();   break;
			case DISABLED:   zeroMotors();        break;
			}
		output();
		LCD();
		nextLoopIteration();
		}
	}
